[package]
name = "dynamic-streaming"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies]
glium = { version = "0.6", default-features = false, features = ["glutin"] }
